version: "2"
services:
  nginx:
    image: nginx:1.23
    restart: unless-stopped
    ports:
    - "80:80"
    environment:
    - NGINX_PORT=80
    volumes:
    - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - "api"
  api:
    build: .
    restart: unless-stopped
    volumes: 
    - ./main.py:/code/main.py
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flexeo
      POSTGRES_DB: flexeo
      POSTGRES_PASSWORD: flexeo
  