version: "2"
services:
  nginx:
    image: nginx
    ports:
    - "80:80"
    environment:
    - NGINX_PORT=80
    volumes:
    - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - "api"
  api:
    build: .
    volumes: 
    - ./main.py:/code/main.py
    ports:
      - "8080:8080"